config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "admin/sessions" }

  namespace :admin do
    resources :programs, :categories, :school_levels, :users, :roles
  end

  get "contact", to: "messages#new", as: "contact"
  post "contact", to: "messages#create"

  resources :bookings
  resources :programs, only: [:index, :show]
  resources :categories, only: [:show]
  resources :school_levels, only: [:show]
  
  root "programs#index"

  get "*path", to: "route_glob#index"
end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :delivery_mode

  has_many :bookings
  has_many :suitabilities
  has_many :school_levels, through: :suitabilities

  mount_uploader :image, ImageUploader
  validate :image_size
  validates_presence_of :program_title, :program_description, :program_fee, :duration, :topics, :group_size_min, :group_size_max, :time_am, :time_pm

  scope :sort_by_name, -> { order(program_title: :ASC) }

  def self.search(query)
    where("program_title LIKE ? or program_description LIKE ?", "%#{query}%", "%#{query}%")
  end

  private

    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end
end

app/controllers/admin/programs_controller.rb
class Admin::ProgramsController < Admin::ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @programs = Program.search(params[:search]).sort_by_name.paginate(page: params[:page], per_page: 10)
    else
      @programs = Program.sort_by_name.paginate(page: params[:page], per_page: 10)
    end
  end

  def show
  end

  def new
    @program = Program.new
    @school_levels = SchoolLevel.all
  end

  def create
    @program = Program.new(program_params)
    @program.user_id = current_user.id
    @school_levels = SchoolLevel.all
    if @program.save
      flash[:success] = "Program successfully created"
      redirect_to admin_program_path(@program)
    else
      render 'new'
    end
  end

  def edit
    @school_levels = SchoolLevel.all
  end

  def update
    if @program.update_attributes(program_params)
      flash[:success] = "Program successfully updated"
      redirect_to admin_program_path(@program)
    else
      render 'edit'
    end
  end

  def destroy
    @program.destroy
    flash[:danger] = "Program #{@program.program_title} successfully deleted"
    redirect_to admin_programs_path
  end

  private

    def program_params
      params.require(:program).permit(:program_title, :program_description, :program_fee, :duration, :image, :image_title, :topics, :group_size_min, :group_size_max, :time_am, :time_pm, :user_id, :category_id, :delivery_mode_id, school_level_ids: [])
    end

    def set_program
      @program = Program.find(params[:id])
    end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def index
    all_programs = Program.all

    if params[:search]
      @programs = all_programs.search(params[:search]).sort_by_name.paginate(page: params[:page], per_page: 10)
    else
      @programs = all_programs.sort_by_name.paginate(page: params[:page], per_page: 10)
    end

    @categories = Category.all
    @school_levels = SchoolLevel.all
    @latest_program = all_programs.last
  end

  def show
    @categories = Category.all
    @school_levels = SchoolLevel.all
    @program = Program.find(params[:id])
  end
end

app/helpers/admin/programs_helper.rb
module Admin::ProgramsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/admin/programs/_form.html.erb
<%= form_for [:admin, @program] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label :program_title, "Title" %>
    <%= f.text_field :program_title, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :program_description, "Description" %>
    <%= f.text_area :program_description, rows: 5, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :program_fee, "Cost per student (AUD)" %>
    <%= f.number_field :program_fee, step: 0.01, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :topics %>
    <%= f.text_field :topics, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :group_size_min, "Min group size" %>
    <%= f.number_field :group_size_min, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :group_size_max, "Max group size" %>
    <%= f.number_field :group_size_max, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :duration, "Duration (hrs)" %>
    <%= f.number_field :duration, step: 0.01, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :time_am, "AM time" %>
    <%= f.time_field :time_am, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :time_pm, "PM time" %>
    <%= f.time_field :time_pm, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id, "Category" %>
    <%= f.collection_select :category_id, Category.all, :id, :name, { include_blank: "Select one" }, class: "form-control", id: "categories" %>
  </div>
  <div class="form-group">
    <%= f.label :delivery_mode, "Mode of delivery" %>
    <%= f.select :delivery_mode_id, DeliveryMode.all.collect{ |x| [x.name, x.id] }, { include_blank: "Select one" }, class: "form-control", id: "deliveries" %>
  </div>
  <div class="form-group years">
    <%= f.label :school_level, "Target audience" %><br />
    <%= hidden_field_tag "program[school_level_ids][]", nil %>
    <div>
      <% @school_levels.each do |school_level| %>
        <span class="checkbox-list">
          <%= check_box_tag "program[school_level_ids][]", school_level.id, @program.school_levels.include?(school_level), id: "school_level_id_#{school_level.id}" %>
          <%= school_level.name %>
        </span>
      <% end %>
    </div>
  </div>
  <span class="program-image">
    <%= f.file_field :image %>
  </span>  
  <br />
  <%= f.submit @program.new_record? ? "Create program" : "Update program", class: "btn admin-btn admin-create-btn" %><%= link_to "Go back to list", admin_programs_path, class: "btn admin-btn admin-cancel-btn" %>
<% end %>

app/views/admin/programs/edit.html.erb
<% title "Edit program" %>
<div class="clearfix main_content floatleft">       
  <div class="clearfix content">
    <div class="contact_us">
      <h1>Edit a program</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/programs/index.html.erb
<% title "Programs" %>
<h1>Manage programs <%= link_to "Create new", new_admin_program_path, class: "btn admin-btn admin-create-btn floatright" %></h1>
<% if @programs.exists? %>
  <div class="clearfix well">
    <%= will_paginate @programs %>
    <table class="table table-striped">
      <tr>
        <th>Category</th>
        <th>Title</th>
        <th>School level</th>
        <th>Uploaded by</th>
        <th>Created at</th>
        <th>Actions</th>
      </tr>
      <% @programs.each do |program| %>
        <tr>
          <td><%= program.category.name %></td>
          <td><%= link_to program.program_title, admin_program_path(program), class: "program-link" %></td>
          <td><%= program.school_levels.map(&:name).join(", ") %></td>
          <td><%= full_name(program.user.first_name, program.user.last_name) %></td>
          <td><%= format_date(program.created_at) %></td>
          <td><%= link_to "Edit", edit_admin_program_path(program), class: "btn admin-btn admin-btn-warning" %><%= link_to "Delete", admin_program_path(program), method: :delete, data: { confirm: "Are you sure?" }, class: "btn admin-btn admin-btn-danger" %></td>
        </tr>
      <% end %>
    </table>
    <%= will_paginate @programs %>
  </div>
<% else %>
  <p>There are no programs to show.</p>
<% end %>

app/views/admin/programs/new.html.erb
<div class="clearfix main_content floatleft">       
  <div class="clearfix content">
    <div class="contact_us">
      <h1>Add a new program</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/programs/show.html.erb
<% title @program.program_title %>
<div class="clearfix content">
  <div class="programs-show">
    <h1><strong><%= @program.program_title.upcase %></strong></h1>
  <div class="programs-show-left">
    <%= image_tag @program.image.url if @program.image? %>
  </div>
  <div class="programs-show-right">
    <h3>Program details</h3>
    <ul>
      <li><strong>Category:</strong> <%= @program.category.name %></li>
      <li><strong>Cost per student:</strong> <%= free?(@program.id)%></li>
      <li><strong>Topics:</strong> <%= @program.topics %></li>
      <li><strong>Group size:</strong> <%= @program.group_size_min %> minimum, <%= @program.group_size_max %> maximum</li>
      <li><strong>Duration:</strong> <%= @program.duration %> hrs</li>
      <li><strong>Start times:</strong> <%= @program.time_am.strftime("%l:%M %p") %>, <%= @program.time_pm.strftime("%l:%M %p") %></li>
      <li><strong>Mode of delivery:</strong> <%= @program.delivery_mode.name %></li>
      <li><strong>Target audience:</strong> <%= @program.school_levels.map(&:name).join(", ") %></li>
      <li><strong>Date created:</strong> <%= format_date(@program.created_at) %></li>
      <li><strong>Created by:</strong> <%= full_name(@program.user.first_name, @program.user.last_name) %></li>
      <li><strong>Last update by:</strong> <%= full_name(@program.user.first_name, @program.user.last_name) %> on <%= format_date(@program.updated_at) %></li>
    </ul>
  </div>
  <div class="programs-show-description">
    <h4>Description</h4>
    <p><%= @program.program_description %></p>
    <hr>
    <h3>Admin actions</h3>
    <%= link_to "Back", admin_programs_path, class: "program-link" %> | <%= link_to "Edit", edit_admin_program_path(@program), class: "program-link" %> | <%= link_to "Delete", admin_program_path(@program), method: :delete, data: { confirm: "Are you sure?" }, class: "program-link" %>
  </div>
</div>
</div>