config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "admin/sessions" }

  namespace :admin do
    resources :programs, :categories, :school_levels, :users, :roles
  end

  get "contact", to: "messages#new", as: "contact"
  post "contact", to: "messages#create"

  resources :bookings
  resources :programs, only: [:index, :show]
  resources :categories, only: [:show]
  resources :school_levels, only: [:show]
  
  root "programs#index"

  get "*path", to: "route_glob#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :program
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :programs
end

app/models/delivery_mode.rb
class DeliveryMode < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,    presence: true,
                      length: { minimum: 10, maximum: 50 }
  validates :email,   presence: true,
                      length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX }
  validates :content, presence: true
end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :delivery_mode

  has_many :bookings
  has_many :suitabilities
  has_many :school_levels, through: :suitabilities

  mount_uploader :image, ImageUploader
  validate :image_size
  validates_presence_of :program_title, :program_description, :program_fee, :duration, :topics, :group_size_min, :group_size_max, :time_am, :time_pm

  scope :sort_by_name, -> { order(program_title: :ASC) }

  def self.search(query)
    where("program_title LIKE ? or program_description LIKE ?", "%#{query}%", "%#{query}%")
  end

  private

    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/school_level.rb
class SchoolLevel < ActiveRecord::Base
  has_many :suitabilities
  has_many :programs, through: :suitabilities
end

app/models/suitability.rb
class Suitability < ActiveRecord::Base
  belongs_to :program
  belongs_to :school_level
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable, :trackable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  belongs_to :role

  has_many :customers, class_name: "User", foreign_key: :creator_id
  belongs_to :creator, class_name: "User", optional: true

  has_many :programs

  has_many :bookings

  scope :admin_email, -> { where(role_id: 1).order(email: :ASC) }
  scope :admins_first, -> { order(role_id: :ASC).order(email: :ASC) }

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false }
  validates_presence_of :first_name, :last_name
  # validation happens before save, app throws an error about missing role if before_save is used
  before_validation :assign_role

  before_save :downcase_email

  def admin?
    self.role.name == "Admin"
  end

  def manager?
    self.role.name == "Manager"
  end

  def regular?
    self.role.name == "Regular"
  end

  private

    # default user to Regular upon creation
    def assign_role
      self.role = Role.find_by(name: "Regular") if self.role.nil?
    end

    def downcase_email
      self.email = email.downcase
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  # before_action :set_program, only: [:new, :create]
  # before_action :set_user, only: [:new, :create]
  before_action :set_resources, only: [:index, :new]

  def index
    @bookings = Booking.all    
  end

  def show
  end

  def new
    @booking = Booking.new
    @program = Program.find_by_id(params[:program_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.program = Program.find_by_id(params[:program_id])
    @booking.user = current_user
    if @booking.save
      flash[:success] = "Program successfully booked"
      redirect_to bookings_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @booking.update_attributes(booking_params)
      flash[:success] = "Booking successfully updated"
      redirect_to bookings_path
    else
      render 'edit'
    end
  end

  def destroy
    @booking.destroy
    flash[:danger] = "Booking successfully removed"
    redirect_to bookings_path
  end

  private

    def set_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:preferred_date, :preferred_time, :notes, :program_id, :user_id)
    end

    def set_resources
      @categories = Category.all
      @school_levels = SchoolLevel.all
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @school_levels = SchoolLevel.all
    @category = @categories.find(params[:id])
    @programs = @category.programs.sort_by_name.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @categories = Category.all
    @school_levels = SchoolLevel.all
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
  end

  private

    def message_params
      params.require(:message).permit(:name, :email, :subject, :content)
    end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def index
    all_programs = Program.all

    if params[:search]
      @programs = all_programs.search(params[:search]).sort_by_name.paginate(page: params[:page], per_page: 10)
    else
      @programs = all_programs.sort_by_name.paginate(page: params[:page], per_page: 10)
    end

    @categories = Category.all
    @school_levels = SchoolLevel.all
    @latest_program = all_programs.last
  end

  def show
    @categories = Category.all
    @school_levels = SchoolLevel.all
    @program = Program.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # for seeding
  def company_bs
    Faker::Company.bs.capitalize + "!"
  end

  # for seeding
  def hipster_statements
    Faker::Hipster.sentences(5).join(" ")
  end

  # for sidebar, programs view for regular users
  def temp_popular_programs
    content_tag :li do
      content_tag :a, Faker::Hipster.sentence
    end
  end

  # for assigning the active class in admin views
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end

  # for showing full name
  def full_name(first_name, last_name)
    first_name + " " + last_name 
  end

  # for program fee
  def free?(course)
    @program.program_fee == 0 ? "Free" : "$%.2f" % @program.program_fee
  end

  # page title
  def title(page_title="")
    content_for(:title) { page_title }
  end

  # time format
  def format_time(input_time)
    input_time.strftime("%l:%M %p")
  end

  # datetime format
  def format_date(input_date)
    input_date.strftime("%d %B %Y at %l:%M %p")
  end

  def format_date_only(input_date)
    input_date.strftime("%d %B %Y")
  end

  # capitalize
  def proper_case(string)
    string.split.map(&:capitalize).join(" ")
  end

  # for finding the current controller
  def current_controller
    params[:controller].split("/").first
  end

  # dont show sidebar when booking
  def bookings_controller?
    current_controller == "bookings"
  end

  # any controller for regular users
  def any_controller_for_regulars?
    current_controller == "programs" || current_controller == "school_levels" || current_controller == "categories" || current_controller == "messages" || bookings_controller?
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper

  def set_program
    Program.find_by_id(params[:program_id]).program_title
  end

  def set_user
    user = current_user
    full_name(user.first_name, user.last_name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/school_levels_helper.rb
module SchoolLevelsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingSystem | <%= content_for?(:title) ? yield(:title) : "Admin" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oswald:400,300,700' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "shared/shim" %>
  </head>

  <body>
    <section id="header_area">
      <%= render "shared/header" %>
    </section>
    
    <section id="content_area">
      <div class="clearfix wrapper main_content_area">
        <%= render "shared/flash_message" %>
        <%= yield %>
      </div>
    </section>
    
    <section id="footer_top_area">
      <%= render "shared/footer_top" %>
    </section>
    
    <section id="footer_bottom_area">
      <%= render "shared/footer_bottom" %>
    </section>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    The form contains <%= pluralize(object.errors.count, "error") %>
    <div class="alert alert-danger">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% if flash.any? %>
  <% flash.each do |message_type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p>Copyright &copy; 2017 | Online Booking System for Schools</p>
</footer>

app/views/shared/_footer_bottom.html.erb
<div class="clearfix wrapper footer_bottom">
  <div class="clearfix copyright floatleft">
    <p> Copyright &copy; 2017 <span>Online Booking System</span></p>
  </div>
  <div class="clearfix social floatright">
    <ul>
      <li><a class="tooltip" title="Facebook" href=""><i class="fa fa-facebook-square"></i></a></li>
      <li><a class="tooltip" title="Twitter" href=""><i class="fa fa-twitter-square"></i></a></li>
      <li><a class="tooltip" title="Google+" href=""><i class="fa fa-google-plus-square"></i></a></li>
      <li><a class="tooltip" title="LinkedIn" href=""><i class="fa fa-linkedin-square"></i></a></li>
      <li><a class="tooltip" title="tumblr" href=""><i class="fa fa-tumblr-square"></i></a></li>
      <li><a class="tooltip" title="Pinterest" href=""><i class="fa fa-pinterest-square"></i></a></li>
      <li><a class="tooltip" title="RSS Feed" href=""><i class="fa fa-rss-square"></i></a></li>
      <li><a class="tooltip" title="Sitemap" href=""><i class="fa fa-sitemap"></i> </a></li>
    </ul>
  </div>
</div>

app/views/shared/_footer_top.html.erb
<div class="clearfix wrapper footer_top">
  <div class="clearfix footer_top_container">
    <div class="clearfix single_footer_top floatleft">
      <h2>About this project</h2>
      <p>Status: Ongoing</p>
      <p>This platform emulates an online booking system that allows school staff to book for enrichment programs offered by informal learning institutions like museums or private educational vendors.</p>
    </div>
    <div class="clearfix single_footer_top floatleft">
      <h2>Features</h2>
      <p>Please check my <a href="https://github.com/emesc/booking_system" target="_blank" rel="noopener">Github</a> page for what are done, being done and will be done.</p>
    </div>
    <div class="clearfix single_footer_top floatleft">
      <h2>Useful Links</h2>
      <ul>
        <li><a href="">Important links of this site</a></li>
        <li><a href="">Important links of this site</a></li>
        <li><a href="">Important links of this site</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="wrapper header">
  <%# if params[:controller].split("/").first == "programs" %>
  <% if any_controller_for_regulars? %>
    <div class="clearfix header_top">
      <div class="clearfix logo floatleft">
        <a href="<%= root_path %>"><h1><span>Testing Program</span> Booking</h1></a>
      </div>
      <div class="clearfix search floatright">
        <%= render "shared/search", search_path: programs_path %>
      </div>
    </div>
    <% unless bookings_controller? %>
      <div class="header_bottom">
        <nav>
          <ul id="nav">
            <li><%= link_to "Home", root_path %></li>
            <li id="dropdown"><a href="">Categories</a>
              <ul>
                <% @categories.each do |category| %>
                  <li><%= link_to category.name, category_path(category) %></li>
                <% end %>
              </ul>
            </li>
            <% @school_levels.each do |school_level| %>
              <li><%= link_to school_level.name, school_level_path(school_level) %></li>
            <% end %>
            <li><%= link_to "Contact us", contact_path %></li>
            </ul>
            <%= render "shared/session_links" %>
        </nav>
      </div>
    <% end %>
  <% elsif user_signed_in? && (current_user.admin? || current_user.manager?) %>
    <div class="clearfix header_top">
      <div class="clearfix logo floatleft">
        <a href="<%= admin_programs_path %>"><h1><span>Booking</span> Manager</h1></a>
      </div>
      <div class="clearfix search floatright">
        <%= render "shared/search", search_path: admin_programs_path %>
      </div>
    </div>
    <div class="header_bottom">
      <nav>
        <ul id="nav">
          <li class="<%= active_class(programs_path) %>"><%= link_to "Home", programs_path %></li>
          <% if current_user.admin? %>
            <li class="<%= active_class(admin_programs_path) %>"><%= link_to "Programs", admin_programs_path %></li>
            <li class="<%= active_class(admin_categories_path) %>"><%= link_to "Categories", admin_categories_path %></li>
            <li class="<%= active_class(admin_school_levels_path) %>"><%= link_to "School Levels", admin_school_levels_path %></li>
            <li class="<%= active_class(admin_roles_path) %>"><%= link_to "User Roles", admin_roles_path %></li>
          <% end %>
          <% if current_user.admin? || current_user.manager? %>
            <li class="<%= active_class(admin_users_path) %>"><%= link_to "Users", admin_users_path %></li>
          <% end %>
        </ul>
        <%= render "shared/session_links" %>
      </nav>
    </div>
  <% end %>
</div>

app/views/shared/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search programs" %>
  <%= submit_tag "Search" %>
<% end %>

app/views/shared/_session_links.html.erb
<ul id="nav" class="floatright">
  <li><%#= debug controller.controller_path %></li>
  <% if user_signed_in? %>
    <li id="dropdown"><a href="">Welcome, <%= full_name(current_user.first_name, current_user.last_name) %></a>
      <ul>
        <% if current_user.admin? %>
          <li><%= link_to "Admin Area", admin_programs_path %></li>
        <% elsif current_user.manager? %>
          <li><%= link_to "Edit profile", edit_admin_user_path(current_user) %></li>
          <li><%= link_to "Your user accounts", admin_users_path %></li>
        <% end %>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </li>
  <% else %>
    <li><%#= link_to "Sign up", new_user_registration_path %></li>
    <li><%= link_to "Sign in", new_user_session_path %></li>
  <% end %>
</ul>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/shared/_sidebar.html.erb
<div class="clearfix sidebar_container floatright">
  <div class="clearfix newsletter">
    <form>
      <h2>Subscribe to our newsletter!</h2>
      <input type="text" placeholder="Email" id="mce-EMAIL"/>
      <input type="text" placeholder="Password" id="mce-TEXT"/>
      <input type="submit" value="Subscribe" id="mc-embedded-subscribe"/>
    </form>
  </div>
  <div class="clearfix sidebar">
    <div class="clearfix single_sidebar">
      <div class="popular_post">
        <div class="sidebar_title"><h2>Most Popular</h2></div>
        <ul>
          <% 5.times do %>
            <%= temp_popular_programs %>
          <% end %>
        </ul>
      </div>
      </div>
    <div class="clearfix single_sidebar">
      <h2>Categories</h2>
      <ul>
        <% @categories.each do |category| %>
          <li class="cat-item"><%= link_to category.name, category_path(category) %>(<%= category.programs.count %>)</li>
        <% end %>
      </ul>
    </div>
    <div class="clearfix single_sidebar">
      <h2>School Year</h2>
      <ul>
        <% @school_levels.each do |school_level| %>
          <li class="level-item"><%= link_to school_level.name, school_level_path(school_level) %> <span>(<%= school_level.programs.count %>)</span></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>