config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "admin/sessions" }

  namespace :admin do
    resources :programs, :categories, :school_levels, :users, :roles
  end

  get "contact", to: "messages#new", as: "contact"
  post "contact", to: "messages#create"

  resources :bookings
  resources :programs, only: [:index, :show]
  resources :categories, only: [:show]
  resources :school_levels, only: [:show]
  
  root "programs#index"

  get "*path", to: "route_glob#index"
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::ApplicationController
  
  def index
    @categories = Category.all
    @school_levels = SchoolLevel.all
    @roles = Role.all
  end

  def show
    @role = Role.find(params[:id])
  end
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/views/admin/roles/index.html.erb
<% title "Roles" %>
<h1>Showing roles</h1>
<% if @roles.exists? %>
  <div class="clearfix well">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
      </tr>
      <% @roles.each do |role| %>
        <tr>
          <td><%= link_to role.name, admin_role_path(role), class: "program-link" %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% else %>
  <p>There are no roles to show.</p>
<% end %>

app/views/admin/roles/show.html.erb
<% title @role.name %>
<div class="clearfix content">
  <div class="programs-show">
    <h1><strong><%= "Associated users for #{@role.name.capitalize} role" %></strong></h1>
    <div class="programs-show-description">
      <% if @role.users.exists? %>
        <div class="role-list">
          <ul>
            <% @role.users.each do |user| %>
              <li><%= link_to full_name(user.first_name, user.last_name), admin_user_path(user) %></li>
            <% end %>
          </ul>
        </div>
      <% else %>
        <p>There are no users under this role.</p>
      <% end %>
      <hr>
      <%= link_to "Back", admin_roles_path, class: "program-link" %>
    </div>
  </div>
</div>