config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "admin/sessions" }

  namespace :admin do
    resources :programs, :categories, :school_levels, :users, :roles
  end

  get "contact", to: "messages#new", as: "contact"
  post "contact", to: "messages#create"

  resources :bookings
  resources :programs, only: [:index, :show]
  resources :categories, only: [:show]
  resources :school_levels, only: [:show]
  
  root "programs#index"

  get "*path", to: "route_glob#index"
end

app/models/school_level.rb
class SchoolLevel < ActiveRecord::Base
  has_many :suitabilities
  has_many :programs, through: :suitabilities
end

app/controllers/admin/school_levels_controller.rb
class Admin::SchoolLevelsController < Admin::ApplicationController
  before_action :set_school_level, only: [:show, :edit, :update, :destroy]

  def index
    @school_levels = SchoolLevel.all
    @categories = Category.all
  end

  def show
    @programs = @school_level.programs.sort_by_name.paginate(page: params[:page], per_page: 10)
  end

  def new
    @school_level = SchoolLevel.new
  end

  def create
    @school_level = SchoolLevel.new(school_level_params)
    if @school_level.save
      flash[:success] = "School level successfully created"
      redirect_to admin_school_levels_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @school_level.update_attributes(school_level_params)
      flash[:success] = "School level successfully updated"
      redirect_to admin_school_levels_path
    else
      redirect_to 'edit'
    end
  end

  def destroy
    @school_level.destroy
    flash[:danger] = "Year #{@school_level.name} successfully deleted"
    redirect_to admin_school_levels_path
  end

  private

    def school_level_params
      params.require(:school_level).permit(:name)
    end

    def set_school_level
      @school_level = SchoolLevel.find(params[:id])
    end
end

app/controllers/school_levels_controller.rb
class SchoolLevelsController < ApplicationController
  
  def show
    @categories = Category.all
    @school_levels = SchoolLevel.all
    @school_level = @school_levels.find(params[:id])
    @programs = @school_level.programs.sort_by_name.paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/admin/school_levels_helper.rb
module Admin::SchoolLevelsHelper
end

app/helpers/school_levels_helper.rb
module SchoolLevelsHelper
end

app/views/admin/school_levels/_form.html.erb
<%= form_for [:admin, @school_level] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <%= f.submit @school_level.new_record? ? "Create school level" : "Update school level", class: "btn admin-btn admin-create-btn" %><%= link_to "Go back to list", admin_school_levels_path, class: "btn admin-btn admin-cancel-btn" %>
<% end %>

app/views/admin/school_levels/edit.html.erb
<% title "Edit school level" %>
<div class="clearfix main_content floatleft">       
  <div class="clearfix content">
    <div class="contact_us">
      <h1>Edit a school level</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/school_levels/index.html.erb
<% title "School levels" %>
<h1>Manage school levels <%= link_to "Create new", new_admin_school_level_path, class: "btn admin-btn admin-create-btn floatright" %></h1>
<% if @school_levels.exists? %>
  <div class="clearfix well">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th>Date created</th>
        <th>Actions</th>
      </tr>
      <% @school_levels.each do |school_level| %>
        <tr>
          <td><%= link_to school_level.name, admin_school_level_path(school_level), class: "program-link" %></td>
          <td><%= format_date(school_level.created_at) %></td>
          <td><%= link_to "Edit", edit_admin_school_level_path(school_level), class: "btn admin-btn admin-btn-warning" %><%= link_to "Delete", admin_school_level_path(school_level), method: :delete, data: { confirm: "Are you sure?" }, class: "btn admin-btn admin-btn-danger" %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% else %>
  <p>There are no school levels to show.</p>
<% end %>

app/views/admin/school_levels/new.html.erb
<% title "New school level" %>
<div class="clearfix main_content floatleft">       
  <div class="clearfix content">
    <div class="contact_us">
      <h1>Add a new school level</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/school_levels/show.html.erb
<% title "Year #{@school_level.name}" %>
<h1>Manage programs for Year <%= @school_level.name %> </h1>
<% if @programs.exists? %>
  <div class="clearfix well">
    <%= will_paginate @programs %>
    <table class="table table-striped">
      <tr>
        <th>Category</th>
        <th>Title</th>
        <th>School level</th>
        <th>Uploaded by</th>
        <th>Created at</th>
        <th>Actions</th>
      </tr>
      <% @programs.each do |program| %>
        <tr>
          <td><%= program.category.name %></td>
          <td><%= link_to program.program_title, admin_program_path(program), class: "program-link" %></td>
          <td><%= program.school_levels.map(&:name).join(", ") %></td>
          <td><%= full_name(program.user.first_name, program.user.last_name) %></td>
          <td><%= format_date(program.created_at) %></td>
          <td><%= link_to "Edit", edit_admin_program_path(program), class: "btn admin-btn admin-btn-warning" %><%= link_to "Delete", admin_program_path(program), method: :delete, data: { confirm: "Are you sure?" }, class: "btn admin-btn admin-btn-danger" %></td>
        </tr>
      <% end %>
    </table>
    <%= will_paginate @programs %>
  </div>
<% else %>
  <p>There are no programs to show.</p>
<% end %>